config/routes.rb
Rails.application.routes.draw do
  resources :trabajos
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trabajo.rb
class Trabajo < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/trabajos_controller.rb
class TrabajosController < ApplicationController
  before_action :set_trabajo, only: [:show, :edit, :update, :destroy]

  # GET /trabajos

  def index
    @trabajos = Trabajo.all
  end

  # GET /trabajos/1

  def show
  end

  # GET /trabajos/new
  def new
    @trabajo = Trabajo.new
  end

  # GET /trabajos/1/edit
  def edit
  end

  # POST /trabajos

  def create
    @trabajo = Trabajo.new(trabajo_params)

    respond_to do |format|
      if @trabajo.save
        format.html { redirect_to @trabajo, notice: 'Trabajo was successfully created.' }

      else
        format.html { render :new }

      end
    end
  end

  # PATCH/PUT /trabajos/1

  def update
    respond_to do |format|
      if @trabajo.update(trabajo_params)
        format.html { redirect_to @trabajo, notice: 'Trabajo was successfully updated.' }

      else
        format.html { render :edit }

      end
    end
  end

  # DELETE /trabajos/1

  def destroy
    @trabajo.destroy
    respond_to do |format|
      format.html { redirect_to trabajos_url, notice: 'Trabajo was successfully destroyed.' }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabajo
      @trabajo = Trabajo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trabajo_params
      params.require(:trabajo).permit(:planta, :ito, :descripcion, :total, :fecha_termino, :avance, :op, :factura, :observaciones, :i1, :i2, :i3, :i4, :i5, :i6, :i7, :i8, :i9, :i10, :i11, :i12, :v1, :v2, :v3, :v4, :v5, :v6, :v7, :v8, :v9, :v10, :v11, :v12, :centro_costo, :supervisor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/trabajos/_form.html.erb
<%= simple_form_for(@trabajo) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :planta %>
    <%= f.input :ito %>
    <%= f.input :descripcion %>
    <%= f.input :total %>
    <%= f.input :fecha_termino %>
    <%= f.input :avance %>
    <%= f.input :op %>
    <%= f.input :factura %>
    <%= f.input :observaciones %>
    <%= f.input :i1 %>
    <%= f.input :i2 %>
    <%= f.input :i3 %>
    <%= f.input :i4 %>
    <%= f.input :i5 %>
    <%= f.input :i6 %>
    <%= f.input :i7 %>
    <%= f.input :i8 %>
    <%= f.input :i9 %>
    <%= f.input :i10 %>
    <%= f.input :i11 %>
    <%= f.input :i12 %>
    <%= f.input :v1 %>
    <%= f.input :v2 %>
    <%= f.input :v3 %>
    <%= f.input :v4 %>
    <%= f.input :v5 %>
    <%= f.input :v6 %>
    <%= f.input :v7 %>
    <%= f.input :v8 %>
    <%= f.input :v9 %>
    <%= f.input :v10 %>
    <%= f.input :v11 %>
    <%= f.input :v12 %>
    <%= f.input :centro_costo %>
    <%= f.input :supervisor %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trabajos/edit.html.erb
<h1>Editing Trabajo</h1>

<%= render 'form', trabajo: @trabajo %>

<%= link_to 'Show', @trabajo %> |
<%= link_to 'Back', trabajos_path %>

app/views/trabajos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trabajos</h1>

<table>
  <thead>
    <tr>
      <th>Planta</th>
      <th>Ito</th>
      <th>Descripcion</th>
      <th>Total</th>
      <th>Fecha termino</th>
      <th>Avance</th>
      <th>Op</th>
      <th>Factura</th>
      <th>Observaciones</th>
      <th>I1</th>
      <th>I2</th>
      <th>I3</th>
      <th>I4</th>
      <th>I5</th>
      <th>I6</th>
      <th>I7</th>
      <th>I8</th>
      <th>I9</th>
      <th>I10</th>
      <th>I11</th>
      <th>I12</th>
      <th>V1</th>
      <th>V2</th>
      <th>V3</th>
      <th>V4</th>
      <th>V5</th>
      <th>V6</th>
      <th>V7</th>
      <th>V8</th>
      <th>V9</th>
      <th>V10</th>
      <th>V11</th>
      <th>V12</th>
      <th>Centro costo</th>
      <th>Supervisor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trabajos.each do |trabajo| %>
      <tr>
        <td><%= trabajo.planta %></td>
        <td><%= trabajo.ito %></td>
        <td><%= trabajo.descripcion %></td>
        <td><%= trabajo.total %></td>
        <td><%= trabajo.fecha_termino %></td>
        <td><%= trabajo.avance %></td>
        <td><%= trabajo.op %></td>
        <td><%= trabajo.factura %></td>
        <td><%= trabajo.observaciones %></td>
        <td><%= trabajo.i1 %></td>
        <td><%= trabajo.i2 %></td>
        <td><%= trabajo.i3 %></td>
        <td><%= trabajo.i4 %></td>
        <td><%= trabajo.i5 %></td>
        <td><%= trabajo.i6 %></td>
        <td><%= trabajo.i7 %></td>
        <td><%= trabajo.i8 %></td>
        <td><%= trabajo.i9 %></td>
        <td><%= trabajo.i10 %></td>
        <td><%= trabajo.i11 %></td>
        <td><%= trabajo.i12 %></td>
        <td><%= trabajo.v1 %></td>
        <td><%= trabajo.v2 %></td>
        <td><%= trabajo.v3 %></td>
        <td><%= trabajo.v4 %></td>
        <td><%= trabajo.v5 %></td>
        <td><%= trabajo.v6 %></td>
        <td><%= trabajo.v7 %></td>
        <td><%= trabajo.v8 %></td>
        <td><%= trabajo.v9 %></td>
        <td><%= trabajo.v10 %></td>
        <td><%= trabajo.v11 %></td>
        <td><%= trabajo.v12 %></td>
        <td><%= trabajo.centro_costo %></td>
        <td><%= trabajo.supervisor %></td>
        <td><%= link_to 'Show', trabajo %></td>
        <td><%= link_to 'Edit', edit_trabajo_path(trabajo) %></td>
        <td><%= link_to 'Destroy', trabajo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trabajo', new_trabajo_path %>

app/views/trabajos/new.html.erb
<h1>New Trabajo</h1>

<%= render 'form', trabajo: @trabajo %>

<%= link_to 'Back', trabajos_path %>

app/views/trabajos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Planta:</strong>
  <%= @trabajo.planta %>
</p>

<p>
  <strong>Ito:</strong>
  <%= @trabajo.ito %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @trabajo.descripcion %>
</p>

<p>
  <strong>Total:</strong>
  <%= @trabajo.total %>
</p>

<p>
  <strong>Fecha termino:</strong>
  <%= @trabajo.fecha_termino %>
</p>

<p>
  <strong>Avance:</strong>
  <%= @trabajo.avance %>
</p>

<p>
  <strong>Op:</strong>
  <%= @trabajo.op %>
</p>

<p>
  <strong>Factura:</strong>
  <%= @trabajo.factura %>
</p>

<p>
  <strong>Observaciones:</strong>
  <%= @trabajo.observaciones %>
</p>

<p>
  <strong>I1:</strong>
  <%= @trabajo.i1 %>
</p>

<p>
  <strong>I2:</strong>
  <%= @trabajo.i2 %>
</p>

<p>
  <strong>I3:</strong>
  <%= @trabajo.i3 %>
</p>

<p>
  <strong>I4:</strong>
  <%= @trabajo.i4 %>
</p>

<p>
  <strong>I5:</strong>
  <%= @trabajo.i5 %>
</p>

<p>
  <strong>I6:</strong>
  <%= @trabajo.i6 %>
</p>

<p>
  <strong>I7:</strong>
  <%= @trabajo.i7 %>
</p>

<p>
  <strong>I8:</strong>
  <%= @trabajo.i8 %>
</p>

<p>
  <strong>I9:</strong>
  <%= @trabajo.i9 %>
</p>

<p>
  <strong>I10:</strong>
  <%= @trabajo.i10 %>
</p>

<p>
  <strong>I11:</strong>
  <%= @trabajo.i11 %>
</p>

<p>
  <strong>I12:</strong>
  <%= @trabajo.i12 %>
</p>

<p>
  <strong>V1:</strong>
  <%= @trabajo.v1 %>
</p>

<p>
  <strong>V2:</strong>
  <%= @trabajo.v2 %>
</p>

<p>
  <strong>V3:</strong>
  <%= @trabajo.v3 %>
</p>

<p>
  <strong>V4:</strong>
  <%= @trabajo.v4 %>
</p>

<p>
  <strong>V5:</strong>
  <%= @trabajo.v5 %>
</p>

<p>
  <strong>V6:</strong>
  <%= @trabajo.v6 %>
</p>

<p>
  <strong>V7:</strong>
  <%= @trabajo.v7 %>
</p>

<p>
  <strong>V8:</strong>
  <%= @trabajo.v8 %>
</p>

<p>
  <strong>V9:</strong>
  <%= @trabajo.v9 %>
</p>

<p>
  <strong>V10:</strong>
  <%= @trabajo.v10 %>
</p>

<p>
  <strong>V11:</strong>
  <%= @trabajo.v11 %>
</p>

<p>
  <strong>V12:</strong>
  <%= @trabajo.v12 %>
</p>

<p>
  <strong>Centro costo:</strong>
  <%= @trabajo.centro_costo %>
</p>

<p>
  <strong>Supervisor:</strong>
  <%= @trabajo.supervisor %>
</p>

<%= link_to 'Edit', edit_trabajo_path(@trabajo) %> |
<%= link_to 'Back', trabajos_path %>